// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ8RiHT9RubQmdN7S1NHqlZMH_1S0T4Sc',
    appId: '1:122088173393:web:baddec265f5914fab6ad70',
    messagingSenderId: '122088173393',
    projectId: 'monocle-chat',
    authDomain: 'monocle-chat.firebaseapp.com',
    databaseURL: 'https://monocle-chat-default-rtdb.firebaseio.com',
    storageBucket: 'monocle-chat.firebasestorage.app',
    measurementId: 'G-BDBHJJR3G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrW7D2YZDXjjSuqu0rS--T39J8LJC1qWw',
    appId: '1:122088173393:android:5a3a8ad80f77d59db6ad70',
    messagingSenderId: '122088173393',
    projectId: 'monocle-chat',
    databaseURL: 'https://monocle-chat-default-rtdb.firebaseio.com',
    storageBucket: 'monocle-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDd-99aXMx1cd320C7Ucujg0x-qL_rXw',
    appId: '1:122088173393:ios:4fe61f539253a7eab6ad70',
    messagingSenderId: '122088173393',
    projectId: 'monocle-chat',
    databaseURL: 'https://monocle-chat-default-rtdb.firebaseio.com',
    storageBucket: 'monocle-chat.firebasestorage.app',
    iosClientId: '122088173393-55nm0hqprb79uab5mflm86prmog3bg63.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
